### ISSUE TITLE
Temperature sensor enable value and mask?

### ISSUE THREAD

**Issue by deviousasti** [stm32duino/LSM303AGR#13]
In the driver for the temperature sensor, the enum is defined as:

```c
/*******************************************************************************
* Register      : TEMP_CFG_REG
* Address       : 0X1F
* Bit Group Name: TEMP_EN
* Permission    : RW
*******************************************************************************/
typedef enum {
  	LSM303AGR_ACC_TEMP_EN_DISABLED 		 =0x00,
  	LSM303AGR_ACC_TEMP_EN_ENABLED 		 =0x40,
} LSM303AGR_ACC_TEMP_EN_t;

#define  	LSM303AGR_ACC_TEMP_EN_MASK  	0x40
```

However, in the datasheet, 

![image](https://user-images.githubusercontent.com/2375486/75097783-abaeaa80-55d4-11ea-9d98-bb9208b0169e.png)

It doesn't work if only the second left-most bit is set. 
0x40 should be 0xC0.

**Comment by cparata** [comment]
Thanks for the fix. I updated accordingly the driver.
Best Regards,
Carlo
