### ISSUE TITLE
the sensor stops to work with Arduino Due

### ISSUE THREAD

**Issue by tanouno** [stm32duino/LSM303AGR#19]
Hello,
I have a big project on Arduino Due and I have continuosly issues with the sensor, so I tried to use the example file. I'm attaching the serial output below. After a while the comunication becomes slow and the magnetic measurements are zero, the others completely wrong. If I reset the Arduino the values change again, but there are still wrong. The issue is not related to the library version, because I got it with different versions. Last but not least important information is that I got 2 devices and with both I got the same behaviour.
Could you give me any suggestion?
regards

| Acc[mg]: 16 0 995 | Mag[mGauss]: -25 213 -382 | Temp[C]: 24.00 |
| Acc[mg]: 23 -7 987 | Mag[mGauss]: -25 202 -378 | Temp[C]: 24.00 |
| Acc[mg]: 16 -11 979 | Mag[mGauss]: -28 207 -378 | Temp[C]: 24.00 |
| Acc[mg]: 23 -11 979 | Mag[mGauss]: -28 205 -384 | Temp[C]: 24.00 |
| Acc[mg]: 27 -19 979 | Mag[mGauss]: -28 205 -376 | Temp[C]: 24.00 | 
| Acc[mg]: 27 -11 987 | Mag[mGauss]: -30 204 -379 | Temp[C]: 24.00 |
| Acc[mg]: 23 -15 979 | Mag[mGauss]: -27 208 -369 | Temp[C]: 24.00 |
| Acc[mg]: 31 -11 975 | Mag[mGauss]: -34 208 -376 | Temp[C]: 24.00 |
| Acc[mg]: 23 -7 979 | Mag[mGauss]: -28 207 -384 | Temp[C]: 24.00 | 
| Acc[mg]: 23 -15 987 | Mag[mGauss]: -27 207 -385 | Temp[C]: 24.00 | 
| Acc[mg]: 27 -11 975 | Mag[mGauss]: -31 211 -382 | Temp[C]: 24.00 |
| Acc[mg]: 23 -11 991 | Mag[mGauss]: -24 210 -381 | Temp[C]: 24.00 |
| Acc[mg]: 27 0 979 | Mag[mGauss]: -31 208 -373 | Temp[C]: 24.00 |
| Acc[mg]: 20 -15 987 | Mag[mGauss]: -33 211 -375 | Temp[C]: 24.00 | 
| Acc[mg]: 31 -22 991 | Mag[mGauss]: -27 207 -372 | Temp[C]: 24.00 |
| Acc[mg]: 23 -22 983 | Mag[mGauss]: -34 210 -390 | Temp[C]: 24.00 |
| Acc[mg]: 20 -11 971 | Mag[mGauss]: -25 213 -375 | Temp[C]: 24.00 |
| Acc[mg]: 20 -22 987 | Mag[mGauss]: -27 214 -375 | Temp[C]: 24.00 | 
| Acc[mg]: 20 -19 983 | Mag[mGauss]: -22 210 -379 | Temp[C]: 24.00 | 
| Acc[mg]: 23 -15 987 | Mag[mGauss]: -22 211 -378 | Temp[C]: 24.00 |
| Acc[mg]: 20 -7 979 | Mag[mGauss]: -31 207 -384 | Temp[C]: 24.00 |
| Acc[mg]: 20 -7 991 | Mag[mGauss]: -25 208 -379 | Temp[C]: 24.00 | 
| Acc[mg]: 20 -11 987 | Mag[mGauss]: -30 208 -378 | Temp[C]: 24.00 | 
| Acc[mg]: 16 -19 979 | Mag[mGauss]: -30 214 -379 | Temp[C]: 24.00 |
| Acc[mg]: 27 -11 987 | Mag[mGauss]: -22 219 -378 | Temp[C]: 24.00 |
| Acc[mg]: 20 -15 991 | Mag[mGauss]: -36 207 -379 | Temp[C]: 24.00 |
| Acc[mg]: 20 -7 983 | Mag[mGauss]: -27 211 -376 | Temp[C]: 24.00 |
| Acc[mg]: 31 -19 987 | Mag[mGauss]: -24 207 -373 | Temp[C]: 24.00 |
| Acc[mg]: 23 -11 979 | Mag[mGauss]: -24 202 -376 | Temp[C]: 24.00 |
| Acc[mg]: 16 -15 971 | Mag[mGauss]: -25 213 -378 | Temp[C]: 24.00 |
| Acc[mg]: 27 -11 987 | Mag[mGauss]: -33 204 -381 | Temp[C]: 24.00 |
| Acc[mg]: 31 -19 983 | Mag[mGauss]: -19 208 -379 | Temp[C]: 24.00 | 
| Acc[mg]: 27 -19 987 | Mag[mGauss]: -33 205 -376 | Temp[C]: 24.00 |
| Acc[mg]: 20 -11 987 | Mag[mGauss]: -31 207 -364 | Temp[C]: 24.00 |
| Acc[mg]: 23 -7 987 | Mag[mGauss]: -24 208 -376 | Temp[C]: 24.00 | 
| Acc[mg]: 23 -11 987 | Mag[mGauss]: -25 211 -384 | Temp[C]: 24.00 | 
| Acc[mg]: 16 -15 991 | Mag[mGauss]: 0 0 0 | Temp[C]: 24.00 |
| Acc[mg]: 16 -15 991 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 16 -15 991 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 16 -15 991 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 16 -15 991 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 | 
| Acc[mg]: 16 -15 991 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 | 
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 | 
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 | 
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 10 2 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |

After reset:

| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 | 
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 | 
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |
| Acc[mg]: 0 527913 537331964 | Mag[mGauss]: 0 0 0 | Temp[C]: 33.77 |

**Comment by cparata** [comment]
Hi @tanouno ,
what is your hardware setup? Arduino DUE plus X-NUCLEO-IKS01A2? I guess that the issue is on the I2C bus and it is very strange that after a while the I2C communication does not work properly. In order to solve the issue after reset, you can try to add before the "DEV_I2C.begin();" in the setup function the following piece of code:

```
//NOTE: workaround in order to unblock the I2C bus on the Arduino Due
#ifdef ARDUINO_SAM_DUE
   pinMode(71, OUTPUT);
   pinMode(70, OUTPUT);

   for (int i = 0; i<10; i++){
     digitalWrite(70, LOW);
     delay(3);
     digitalWrite(71, HIGH);
     delay(3);
     digitalWrite(70, HIGH);
     delay(3);
     digitalWrite(71, LOW);
     delay(3);
   }
   pinMode(70, INPUT);
   pinMode(71, INPUT);
#endif
//End of workaround
```

Let me know if it works on your side.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Agreed with @cparata 
Some good reading about that:
https://www.i2c-bus.org/i2c-primer/analysing-obscure-problems/blocked-bus/
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiOyo2w7YnwAhXszoUKHVFAB2oQFjAAegQIBBAD&url=https%3A%2F%2Fwww.analog.com%2Fmedia%2Fen%2Ftechnical-documentation%2Fapplication-notes%2F54305147357414AN686_0.pdf&usg=AOvVaw3qJOUBnpV5EAG4LWn_HL9K

@cparata I wonder if we should not add a `Wire.reset()` function in our API?

**Comment by cparata** [comment]
Hi @fpistm ,
I would not know. When would you call the Wire.reset()? Before the Wire.begin()? Maybe the cleanest approach would be to include the "reset" procedure inside the "begin" implementation, but obviously in this way it will work only for STM32 based boards.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Right, anyway this is a core related feature.
Begin could call it by default and user should be able to call it if they catch an error from the Wire api.

**Comment by cparata** [comment]
If we include the "reset" procedure inside the "begin" implementation, I think we don't need to implement a dedicated API for "reset", but a combination of "end" and "begin" should be enough to unlock the I2C bus

**Comment by fpistm** [comment]
Yes this need to be studied later at core level as an enhancement.
No specific  link to this issue as it uses an other core. Was just an idea 😉

**Comment by cparata** [comment]
Hi @tanouno ,
today I did some tests with Arduino DUE and X-NUCLEO-IKS01A2 and I did not see any particular issue on the output data. The application read data from LSM303AGR sensor correctly for more than 30 minutes. So, I suspect that there is an issue in your hardware setup. Please, check that in your hardware setup you have the Pull-Up resistors for I2C pins otherwise you risk some instabilities on the I2C bus. For the reset issue, instead, you can try the workaround that I proposed in the message above.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Hi @tanouno 
any update on this ?
Thanks in advance.

**Comment by tanouno** [comment]
Hi Frederic,
Thank you for your inquiry, but I tried to follow the hint of Carlo without any result. When I wrote, I loaded the library's example  without any modification, so to be honest I didn’t understand which hardware configuration could be wrong. First I connected the  scl and sda pins to Wire1 (on Arduino DUE pin SCL1 and SDA1) then to Wire (pins 21 and 20). The issue stills persist. I haven't been time to change the program with begin and end for each transaction.
Best regards

**Comment by cparata** [comment]
Hi @tanouno ,
did you check if you are using the Pull-Up resistors on SCL and SDA pins? Maybe in your hardware setup, you need to put them externally.
Best Regards,
Carlo

**Comment by tanouno** [comment]
Hi Carlo,
I use a breakout of Adafruit for the LSM303AGR connected directly with Arduino Due.
Looking for informations, I found:
I2C Logic Pins

SCL - I2C clock pin, connect to your microcontroller's I2C clock line. This pin is level shifted so you can use 3-5V logic, and there's a 10K pullup on this pin.
SDA -I2C data pin, connect to your microcontroller's I2C data line. This pin is level shifted so you can use 3-5V logic, and there's a 10K pullup on this pin.




Regards

**Comment by cparata** [comment]
Ok clear, thanks. At this point the only issue could be the communications on the fly wires. I tried the sample sketch with a [X-NUCLEO-IKS01A2](https://www.st.com/content/st_com/en/products/ecosystems/stm32-open-development-environment/stm32-nucleo-expansion-boards/stm32-ode-sense-hw/x-nucleo-iks01a2.html) and the Arduino DUE and I did not find any instability on the I2C bus. I was able to read correctly the values of LSM303AGR for 30 minutes continuously.
Best Regards,
Carlo

**Comment by fpistm** [comment]
You told that

> The issue is not related to the library version, because I got it with different versions.

You mean you tested several libraries?
Did you test this one from Adafruit:
https://github.com/adafruit/Adafruit_LIS2MDL library as you used Adafruit boards.

**Comment by tanouno** [comment]
I choose the STM Library because the adafruit needs to work the Adafruit_sensor Library and I decided not to use that on my project. I need a library easy and simple for my project. I used some version of STM library.
It’s a couple of days that I’m trying  X-NUCLEO-IKS01A2 and it seems much better.

**Comment by fpistm** [comment]
OK make sense. Anyway I do not have any clue for you and as @cparata stated before he do not not see any issue during his test.
