### ISSUE TITLE
DisableSelfTest cannot return LSM303AGR_ACC_STATUS_OK

### ISSUE THREAD

**Issue by etakata** [stm32duino/LSM303AGR#20]
`DisableSelfTest()` in `LSM303AGR_ACC_Sensor.cpp` doesn't work well.
It returns  LSM303AGR_ACC_STATUS_ERROR in spite of success.

I think this is the reason, [here](https://github.com/stm32duino/LSM303AGR/blob/f40cd87cb52076f166dad1eb31f3e6728b9d6401/src/LSM303AGR_ACC_Sensor.cpp#L628)

my suggestion:
```cpp
LSM303AGR_ACC_StatusTypeDef LSM303AGR_ACC_Sensor::DisableSelfTest(void)
{    
    if (LSM303AGR_ACC_W_SelfTest(this, LSM303AGR_ACC_ST_DISABLED) == MEMS_ERROR)
        return LSM303AGR_ACC_STATUS_ERROR;

    return LSM303AGR_ACC_STATUS_OK;
}
```

**Comment by cparata** [comment]
Hi @etakata ,
thanks a lot for your contribution. Fix integrated in the main branch and new release generated.
Best Regards,
Carlo
