### ISSUE TITLE
Declare signed or unsigned when bit shifting

### ISSUE THREAD

**Issue by etakata** [stm32duino/LSM303AGR#21]
I think `LSM303AGR_ACC_Sensor::GetAxesRaw(int16_t *pData)` is better to provide signed accelerometer raw data.

In the current implementation, the high-order bits are 0-filled even for negative values.

https://github.com/stm32duino/LSM303AGR/blob/d6141e59ee613baf88669dcea688ec5688277c22/src/LSM303AGR_ACC_Sensor.cpp#L417-L419

my suggestion:
```
  pData[0] = ( (int16_t)( ( ( ( int16_t )regValue[1] ) << 8 ) + ( int16_t )regValue[0] ) >> shift );
  pData[1] = ( (int16_t)( ( ( ( int16_t )regValue[3] ) << 8 ) + ( int16_t )regValue[2] ) >> shift );
  pData[2] = ( (int16_t)( ( ( ( int16_t )regValue[5] ) << 8 ) + ( int16_t )regValue[4] ) >> shift );
```

**Comment by cparata** [comment]
Hi @etakata ,
thanks for the suggestion. I implemented your fix in the main repository and generated a new release of the library.
Best Regards,
Carlo
